#!/bin/bash

set -e
set -x

if [ $# -ne 2 ]
    then
        echo "Wrong number of arguments supplied."
        echo "Usage: $0 <server_url> <deploy_key>."
        exit 1
fi

apt-get update
apt-get install -y python

server_url=$1
deploy_key=$2

apt-get update
apt-get -y install python-dev git supervisor authbind openssl python-virtualenv build-essential python-gmpy2 libgmp-dev libmpfr-dev libmpc-dev libssl-dev python-pip libffi-dev

pip install -U supervisor
/etc/init.d/supervisor start || true

#add user adb
useradd -d /home/adb -s /bin/bash -m adb -g users


cd /opt
git clone https://github.com/huuck/ADBHoney.git

#cd /opt/ADBHoney
#nohup python run.py &

cd /opt/ADBHoney
#ADD INFORMATION To SEND DATA TO HONEY net
cat > /opt/ADBHoney/adbhoney.cfg <<EOF

[honeypot]
hostname = ADB1

address = 0.0.0.0
port = 5555

download_dir = dl/
log_dir = logs/

device_id = device::http://ro.product.name =starltexx;ro.product.model=SM-G960F;ro.product.device=starlte;features=cmd,stat_v2,shell_v2

[output_log]
enabled = true
log_file = adbhoney.log
log_level = info

[output_json]
enabled = true
log_file = adbhoney.json

[database_hpfeeds]
server = $HPF_HOST
port = $HPF_PORT
identifier = $HPF_IDENT
secret = $HPF_SECRET
debug = 0
EOF



# Register sensor with MHN server.
wget $server_url/static/registration.txt -O registration.sh
chmod 755 registration.sh
# Note: this will export the HPF_* variables
. ./registration.sh $server_url $deploy_key "Android Honeypot"

chown -R adb:users /opt/ADBHoney/
touch /etc/authbind/byport/5555
chown adb /etc/authbind/byport/5555
chmod 770 /etc/authbind/byport/5555

# Config for supervisor
cat <<EOF>> /etc/supervisor/conf.d/ADBHoney.conf
[program:ADBHoney]
command=nohup python /opt/adb/run.py &
directory=/opt/ADBHoney
stdout_logfile=/opt/ADBHoney/var/log/ADBHoney/adb.out
stderr_logfile=/opt/ADBHoney/var/log/ADBHoney/adb.err
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=adb
EOF

supervisorctl update
